### ISSUE TITLE
Messing with the CSS

### ISSUE THREAD

**Issue by bosiarquitetura** [bosiarquitetura/aristoteles#2]
Feel free to mess around with the CSS of the site

**Comment by nataliepls** [comment]
Hey can I work on this ?

**Comment by bosiarquitetura** [comment]
Yes, feel free!

**Comment by suraj-sloth** [comment]
#12  I have modified some changes.

**Comment by Majse14** [comment]
Hello! what do you need? :woman:

**Comment by guilhermeorcezi** [comment]
What can I do on this?

**Comment by bosiarquitetura** [comment]
Yes, feel free to do what you think will make the site better
